import { useState } from "react";
import { TradingSystem } from "../types";
import SectionCard from "./SectionCard";

interface Props {
  system: TradingSystem;
  onReset: () => void;
}

export default function ResultPanel({ system, onReset }: Props) {
  const [activeFilter, setActiveFilter] = useState("all");

  const filters = [
    { id: "all", label: "All Sections" },
    { id: "setup", label: "Setup" },
    { id: "strategy", label: "Strategy" },
    { id: "risk", label: "Risk" },
    { id: "backtest", label: "Backtest" },
    { id: "deployment", label: "Deploy" },
  ];

  const filterMap: Record<string, string[]> = {
    setup: ["overview", "setup", "data"],
    strategy: ["strategy", "execution"],
    risk: ["risk"],
    backtest: ["backtest"],
    deployment: ["deployment", "improvements", "disclaimer"],
  };

  const visibleSections = activeFilter === "all"
    ? system.sections
    : system.sections.filter((s) => filterMap[activeFilter]?.includes(s.id));

  // Export as markdown
  const exportMarkdown = () => {
    const md = system.sections.map((s) => {
      let out = `## ${s.title}\n\n${s.content}\n`;
      if (s.code) out += `\n\`\`\`${s.language || "python"}\n${s.code}\n\`\`\`\n`;
      return out;
    }).join("\n---\n\n");

    const full = `# TradeForge AI — Trading System\n**Idea:** ${system.idea}\n**Generated:** ${system.generatedAt}\n\n---\n\n${md}\n\n---\n*Generated by TradeForge AI — For educational purposes only.*`;
    const blob = new Blob([full], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "tradeforge-system.md";
    a.click();
  };

  return (
    <div className="space-y-6">
      {/* Result Header */}
      <div className="bg-slate-900/80 border border-emerald-500/30 rounded-2xl p-5 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="w-2.5 h-2.5 bg-emerald-400 rounded-full animate-pulse" />
            <span className="text-emerald-400 text-xs font-semibold uppercase tracking-wide">System Generated</span>
          </div>
          <p className="text-white font-semibold text-sm md:text-base line-clamp-2">"{system.idea}"</p>
          <p className="text-slate-500 text-xs mt-0.5">Generated at {system.generatedAt}</p>
        </div>
        <div className="flex gap-2 shrink-0">
          <button
            onClick={exportMarkdown}
            className="flex items-center gap-1.5 bg-slate-800 hover:bg-slate-700 border border-slate-600 text-slate-300 hover:text-white text-xs font-medium px-3 py-2 rounded-lg transition-colors"
          >
            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Export .md
          </button>
          <button
            onClick={onReset}
            className="flex items-center gap-1.5 bg-emerald-500/10 hover:bg-emerald-500/20 border border-emerald-500/40 text-emerald-400 text-xs font-medium px-3 py-2 rounded-lg transition-colors"
          >
            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" />
            </svg>
            New Strategy
          </button>
        </div>
      </div>

      {/* Stats strip */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {[
          { label: "Sections", value: system.sections.length.toString(), icon: "📋" },
          { label: "Code Blocks", value: system.sections.filter((s) => s.code).length.toString(), icon: "🐍" },
          { label: "Libraries", value: "8+", icon: "📦" },
          { label: "Deploy Ready", value: "Yes", icon: "🚀" },
        ].map((stat) => (
          <div key={stat.label} className="bg-slate-900/60 border border-slate-700/60 rounded-xl p-3 text-center">
            <div className="text-lg mb-0.5">{stat.icon}</div>
            <div className="text-white font-bold text-lg leading-none">{stat.value}</div>
            <div className="text-slate-500 text-xs mt-0.5">{stat.label}</div>
          </div>
        ))}
      </div>

      {/* Filter tabs */}
      <div className="flex overflow-x-auto gap-2 pb-1">
        {filters.map((f) => (
          <button
            key={f.id}
            onClick={() => setActiveFilter(f.id)}
            className={`shrink-0 text-xs font-semibold px-4 py-2 rounded-lg border transition-all ${
              activeFilter === f.id
                ? "bg-emerald-500/15 border-emerald-500/50 text-emerald-400"
                : "bg-slate-800/60 border-slate-700/60 text-slate-400 hover:text-white hover:border-slate-500"
            }`}
          >
            {f.label}
          </button>
        ))}
      </div>

      {/* Sections */}
      <div className="space-y-3">
        {visibleSections.map((section, idx) => (
          <SectionCard key={section.id} section={section} index={idx} />
        ))}
      </div>

      {/* GitHub note */}
      <div className="bg-slate-900/60 border border-slate-700/40 rounded-2xl p-5">
        <div className="flex items-start gap-3">
          <span className="text-2xl shrink-0">🐙</span>
          <div>
            <h3 className="text-white font-semibold text-sm mb-1">Free GitHub Hosting (No Domain Needed)</h3>
            <p className="text-slate-400 text-xs leading-relaxed">
              Host your dashboard at <code className="bg-slate-800 text-emerald-400 px-1.5 py-0.5 rounded text-xs">https://yourusername.github.io/tradeforge</code>.
              Use <strong className="text-slate-300">GitHub Actions</strong> (free 2000 min/month) to run your strategy on a schedule.
              Store API keys as <strong className="text-slate-300">GitHub Secrets</strong>. Export this system as Markdown and push it to your repo.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
